### ISSUE TITLE
Nasa.js url broken

### ISSUE THREAD

**Issue by Arjhan123** [AndyTheNerd/Storehaus#10]
the url in nasa.js is broken and tries to show tomorrows date

https://api.nasa.gov/planetary/apod?api_key=DEMO_KEY is the url that's broken

**Comment by AndyTheNerd** [comment]
Thanks for the feedback! Discovered sometimes the API likes to set it to tomorrow, so we can pass in the data as a parameter in the future. Will be included in next release :)
